import type { BuildIntent, BuildVersion, HarnessRun } from "../domain/index.js";
import type { LoadedAgent } from "./types.js";
import { TraceRecorder } from "./trace-recorder.js";
import type { ToolRegistry } from "./tool-registry.js";
import { RunStore } from "./run-store.js";
import { ApprovalGate } from "./approval-gate.js";
import { SandboxRunner } from "./sandbox-runner.js";
import { createBuiltinTools } from "./builtin-tools.js";
import { createScopedToolRegistry } from "./scoped-tools.js";

export interface WorkflowResult {
  run: HarnessRun;
  trace: ReturnType<TraceRecorder["all"]>;
  approvals: ReturnType<ApprovalGate["all"]>;
  runDir: string;
}

export interface WorkflowOptions {
  workspaceRoot?: string;
  approvalMode?: "auto" | "manual";
}

export async function runSiteBuildWorkflow(agent: LoadedAgent, intent: BuildIntent, options: WorkflowOptions = {}): Promise<WorkflowResult> {
  const workspaceRoot = options.workspaceRoot ?? "workspace";
  const approvalMode = options.approvalMode ?? "auto";
  const now = new Date().toISOString();
  const recorder = new TraceRecorder();
  const store = new RunStore(workspaceRoot);
  const approvalGate = new ApprovalGate();
  const sandbox = new SandboxRunner(workspaceRoot);
  const { registry: toolRegistry, skipped } = createScopedToolRegistry(
    agent,
    createBuiltinTools({ workspaceRoot, approvalGate, sandbox }),
  );

  const run: HarnessRun = {
    id: crypto.randomUUID(),
    intent,
    currentStep: "build_site",
    status: "running",
    context: {
      wikiIndexPaths: ["workspace/wiki/index.md"],
      loadedEntityIds: [],
      loadedSourceRefs: [],
      visibleArtifacts: [],
      notes: [
        `Loaded agent ${agent.definition.id}`,
        `Local tools: ${agent.localTools.join(", ") || "none"}`,
        `Skipped tools: ${skipped.map((tool) => `${tool.name} (${tool.reason})`).join(", ") || "none"}`,
      ],
    },
    toolTrace: [],
    versions: [],
    createdAt: now,
    updatedAt: now,
  };
  await persist(store, run, recorder, approvalGate);

  const turn = recorder.start("ai.eve.turn", {
    agent: agent.definition.id,
    intent: intent.goal,
    tools: toolRegistry.manifest().map((tool) => tool.name),
  });

  const model = recorder.start("ai.streamText", {
    model: agent.definition.model,
    instructionsLength: agent.instructions.length,
  }, turn.id);

  recorder.end(model, {
    note: "Demo workflow uses deterministic output instead of an external model call.",
  });
  await persist(store, run, recorder, approvalGate);

  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "read_content_model",
    input: { intentId: intent.id },
  });

  const htmlArtifact = [
    "<!doctype html>",
    "<html lang=\"en\">",
    "<head>",
    "  <meta charset=\"utf-8\" />",
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "  <title>Personal Wiki Portfolio</title>",
    "  <style>",
    "    body { margin: 0; font-family: ui-sans-serif, system-ui, sans-serif; background: #f7f7f2; color: #202124; }",
    "    main { max-width: 880px; margin: 0 auto; padding: 72px 24px; }",
    "    h1 { font-size: 48px; line-height: 1; margin: 0 0 16px; }",
    "    p { font-size: 18px; line-height: 1.6; max-width: 680px; }",
    "    .pill { display: inline-block; border: 1px solid #202124; padding: 6px 10px; margin: 6px 6px 0 0; font-size: 13px; }",
    "  </style>",
    "</head>",
    "<body>",
    "  <main>",
    `    <h1>${intent.goal}</h1>`,
    `    <p>Audience: ${intent.audience}. Purpose: ${intent.purpose}. This static artifact was compiled by the durable harness workflow.</p>`,
    "    <div>",
    ...intent.constraints.map((constraint) => `      <span class=\"pill\">${escapeHtml(constraint)}</span>`),
    "    </div>",
    "  </main>",
    "</body>",
    "</html>",
  ].join("\n");

  const artifactMarkdown = [
    "# Personal Wiki Portfolio",
    "",
    `Audience: ${intent.audience}`,
    `Purpose: ${intent.purpose}`,
    "",
    "This artifact was generated by the harness workflow.",
    "",
    "## Trace",
    "",
    "- ai.eve.turn",
    "- ai.streamText",
    "- ai.toolCall",
  ].join("\n");

  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "write_site_file",
    input: {
      path: "site.md",
      content: artifactMarkdown,
    },
  });
  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "write_site_file",
    input: {
      path: "index.html",
      content: htmlArtifact,
    },
  });
  await persist(store, run, recorder, approvalGate);

  const artifactPath = sandbox.artifactDir(run.id);
  run.currentStep = "approval";
  run.status = "awaiting_approval";
  run.updatedAt = new Date().toISOString();
  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "request_approval",
    input: {
      reason: "Approve generated site artifact before validation and version capture.",
      artifactPath,
      autoApprove: approvalMode === "auto",
    },
  });
  await persist(store, run, recorder, approvalGate);

  if (approvalMode === "manual") {
    recorder.end(turn, {
      status: run.status,
      note: "Workflow paused for human approval.",
    });
    await persist(store, run, recorder, approvalGate);
    return { run, trace: recorder.all(), approvals: approvalGate.all(), runDir: store.paths(run.id).runDir };
  }

  run.status = "running";
  await persist(store, run, recorder, approvalGate);

  await validateAndVersion({
    recorder,
    registry: toolRegistry,
    run,
    store,
    approvalGate,
    parentId: turn.id,
    artifactPath,
  });

  recorder.end(turn, {
    status: run.status,
    versionId: run.versions.at(-1)?.id,
  });
  await persist(store, run, recorder, approvalGate);

  return { run, trace: recorder.all(), approvals: approvalGate.all(), runDir: store.paths(run.id).runDir };
}

export async function resumeSiteBuildWorkflow(agent: LoadedAgent, runId: string, options: WorkflowOptions = {}): Promise<WorkflowResult> {
  const workspaceRoot = options.workspaceRoot ?? "workspace";
  const store = new RunStore(workspaceRoot);
  const run = await store.loadRun(runId);
  const existingTrace = await store.loadTrace(runId);
  const existingApprovals = await store.loadApprovals(runId);
  const recorder = new TraceRecorder(existingTrace);
  const approvalGate = new ApprovalGate(existingApprovals);
  const sandbox = new SandboxRunner(workspaceRoot);
  const { registry: toolRegistry } = createScopedToolRegistry(
    agent,
    createBuiltinTools({ workspaceRoot, approvalGate, sandbox }),
  );

  if (run.status !== "awaiting_approval") {
    return { run, trace: recorder.all(), approvals: approvalGate.all(), runDir: store.paths(run.id).runDir };
  }

  const pending = approvalGate.firstPending();
  if (!pending) throw new Error(`Run ${run.id} is awaiting approval but has no pending approval`);
  approvalGate.approve(pending.id);
  run.status = "running";
  run.updatedAt = new Date().toISOString();

  const turn = recorder.start("ai.eve.turn.resume", {
    agent: agent.definition.id,
    runId: run.id,
    approved: pending.id,
  });

  await validateAndVersion({
    recorder,
    registry: toolRegistry,
    run,
    store,
    approvalGate,
    parentId: turn.id,
    artifactPath: pending.artifactPath ?? sandbox.artifactDir(run.id),
  });

  recorder.end(turn, {
    status: run.status,
    versionId: run.versions.at(-1)?.id,
  });
  await persist(store, run, recorder, approvalGate);

  return { run, trace: recorder.all(), approvals: approvalGate.all(), runDir: store.paths(run.id).runDir };
}

async function callTool(input: {
  recorder: TraceRecorder;
  registry: ToolRegistry;
  run: HarnessRun;
  parentId: string;
  name: string;
  input: unknown;
  maxAttempts?: number;
}): Promise<void> {
  const span = input.recorder.start("ai.toolCall", {
    tool: input.name,
    input: input.input,
  }, input.parentId);
  const record = await input.registry.call(input.name, input.input, input.run, {
    maxAttempts: input.maxAttempts ?? 2,
  });
  input.run.toolTrace.push(record);
  input.run.updatedAt = new Date().toISOString();
  if (record.status === "ok") input.recorder.end(span, record);
  else input.recorder.error(span, record);
}

async function persist(store: RunStore, run: HarnessRun, recorder: TraceRecorder, approvalGate: ApprovalGate): Promise<void> {
  await store.saveRun(run);
  await store.saveTrace(run.id, recorder.all());
  await store.saveApprovals(run.id, approvalGate.all());
}

async function validateAndVersion(input: {
  recorder: TraceRecorder;
  registry: ToolRegistry;
  run: HarnessRun;
  store: RunStore;
  approvalGate: ApprovalGate;
  parentId: string;
  artifactPath: string;
}): Promise<void> {
  input.run.currentStep = "validate";
  input.run.updatedAt = new Date().toISOString();
  await callTool({
    recorder: input.recorder,
    registry: input.registry,
    run: input.run,
    parentId: input.parentId,
    name: "run_build",
    input: {
      requiredFiles: ["site.md", "index.html"],
    },
  });

  const validationCall = input.run.toolTrace.at(-1);
  const validationStatus = validationCall?.status === "ok" ? "passed" : "failed";
  const version: BuildVersion = {
    id: crypto.randomUUID(),
    runId: input.run.id,
    artifactPath: input.artifactPath,
    summary: `Created a site artifact plan for ${input.run.intent.audience}.`,
    usedEntityIds: [],
    usedSourceIds: [],
    validationStatus,
    createdAt: new Date().toISOString(),
  };

  input.run.versions.push(version);
  if (!input.run.context.visibleArtifacts.includes(version.artifactPath)) {
    input.run.context.visibleArtifacts.push(version.artifactPath);
  }
  input.run.currentStep = validationStatus === "passed" ? "complete" : "repair";
  input.run.status = validationStatus === "passed" ? "completed" : "failed";
  input.run.updatedAt = new Date().toISOString();
  await persist(input.store, input.run, input.recorder, input.approvalGate);
}

function escapeHtml(input: string): string {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("\"", "&quot;")
    .replaceAll("'", "&#39;");
}
