import type { BuildIntent, BuildVersion, HarnessRun } from "../domain/index.js";
import type { LoadedAgent } from "./types.js";
import { TraceRecorder } from "./trace-recorder.js";
import { ToolRegistry } from "./tool-registry.js";
import { RunStore } from "./run-store.js";
import { ApprovalGate } from "./approval-gate.js";
import { SandboxRunner } from "./sandbox-runner.js";
import { createBuiltinTools } from "./builtin-tools.js";

export interface WorkflowResult {
  run: HarnessRun;
  trace: ReturnType<TraceRecorder["all"]>;
  approvals: ReturnType<ApprovalGate["all"]>;
  runDir: string;
}

export async function runSiteBuildWorkflow(agent: LoadedAgent, intent: BuildIntent, workspaceRoot = "workspace"): Promise<WorkflowResult> {
  const now = new Date().toISOString();
  const recorder = new TraceRecorder();
  const store = new RunStore(workspaceRoot);
  const approvalGate = new ApprovalGate();
  const sandbox = new SandboxRunner(workspaceRoot);
  const toolRegistry = new ToolRegistry();
  for (const tool of createBuiltinTools({ workspaceRoot, approvalGate, sandbox })) {
    toolRegistry.register(tool);
  }

  const run: HarnessRun = {
    id: crypto.randomUUID(),
    intent,
    currentStep: "build_site",
    status: "running",
    context: {
      wikiIndexPaths: ["workspace/wiki/index.md"],
      loadedEntityIds: [],
      loadedSourceRefs: [],
      visibleArtifacts: [],
      notes: [`Loaded agent ${agent.definition.id}`],
    },
    toolTrace: [],
    versions: [],
    createdAt: now,
    updatedAt: now,
  };
  await persist(store, run, recorder, approvalGate);

  const turn = recorder.start("ai.eve.turn", {
    agent: agent.definition.id,
    intent: intent.goal,
    tools: toolRegistry.manifest().map((tool) => tool.name),
  });

  const model = recorder.start("ai.streamText", {
    model: agent.definition.model,
    instructionsLength: agent.instructions.length,
  }, turn.id);

  recorder.end(model, {
    note: "Demo workflow uses deterministic output instead of an external model call.",
  });
  await persist(store, run, recorder, approvalGate);

  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "read_content_model",
    input: { intentId: intent.id },
  });

  const artifactMarkdown = [
    "# Personal Wiki Portfolio",
    "",
    `Audience: ${intent.audience}`,
    `Purpose: ${intent.purpose}`,
    "",
    "This artifact was generated by the harness workflow.",
    "",
    "## Trace",
    "",
    "- ai.eve.turn",
    "- ai.streamText",
    "- ai.toolCall",
  ].join("\n");

  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "write_site_file",
    input: {
      path: "site.md",
      content: artifactMarkdown,
    },
  });
  await persist(store, run, recorder, approvalGate);

  const artifactPath = sandbox.artifactDir(run.id);
  run.currentStep = "approval";
  run.status = "awaiting_approval";
  run.updatedAt = new Date().toISOString();
  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "request_approval",
    input: {
      reason: "Approve generated site artifact before validation and version capture.",
      artifactPath,
      autoApprove: true,
    },
  });
  run.status = "running";
  await persist(store, run, recorder, approvalGate);

  run.currentStep = "validate";
  run.updatedAt = new Date().toISOString();
  await callTool({
    recorder,
    registry: toolRegistry,
    run,
    parentId: turn.id,
    name: "run_build",
    input: {
      requiredFiles: ["site.md"],
    },
  });

  const version: BuildVersion = {
    id: crypto.randomUUID(),
    runId: run.id,
    artifactPath,
    summary: `Created a site artifact plan for ${intent.audience}.`,
    usedEntityIds: [],
    usedSourceIds: [],
    validationStatus: "passed",
    createdAt: new Date().toISOString(),
  };

  run.versions.push(version);
  run.context.visibleArtifacts.push(version.artifactPath);
  run.currentStep = "complete";
  run.status = "completed";
  run.updatedAt = new Date().toISOString();

  recorder.end(turn, {
    status: run.status,
    versionId: version.id,
  });
  await persist(store, run, recorder, approvalGate);

  return { run, trace: recorder.all(), approvals: approvalGate.all(), runDir: store.paths(run.id).runDir };
}

async function callTool(input: {
  recorder: TraceRecorder;
  registry: ToolRegistry;
  run: HarnessRun;
  parentId: string;
  name: string;
  input: unknown;
}): Promise<void> {
  const span = input.recorder.start("ai.toolCall", {
    tool: input.name,
    input: input.input,
  }, input.parentId);
  const record = await input.registry.call(input.name, input.input, input.run);
  input.run.toolTrace.push(record);
  input.run.updatedAt = new Date().toISOString();
  if (record.status === "ok") input.recorder.end(span, record);
  else input.recorder.error(span, record);
}

async function persist(store: RunStore, run: HarnessRun, recorder: TraceRecorder, approvalGate: ApprovalGate): Promise<void> {
  await store.saveRun(run);
  await store.saveTrace(run.id, recorder.all());
  await store.saveApprovals(run.id, approvalGate.all());
}
