export {
  PersonalWikiEngine,
  auditWorkspaceState,
  createWorkspaceToolRegistry,
  createDefaultSourcePolicy,
  createEmptyWorkspaceSnapshot,
  createWikiMutationPlanHandoff,
  createWikiMutationPlanFromSourceDocuments,
  createWikiMutationPlanReviewBatches,
  createWikiSnapshotFromSourceDocuments,
  createReferencedSourceEntry,
  createWorkspaceEvent,
  createWorkspaceManifest,
  describeSourceStorage,
  applyWikiMutationPlan,
  shouldInlineSource,
  sourceDocumentFromManifestEntry,
  summarizeWikiMutationPlan,
  verifyWorkspaceState,
  type CompiledSiteArtifact,
  type PersonalWikiEngineOptions,
  type SiteArtifactFile,
  type SourceIndexStatus,
  type SourceStorageMode,
  type WikiWorkspaceManifest,
  type WorkspaceAdapter,
  type WorkspaceEvent,
  type WorkspaceEventActor,
  type WorkspaceEventKind,
  type WorkspaceVerificationCheck,
  type WorkspaceVerificationReport,
  type WorkspaceVerificationStatus,
  type WorkspaceKind,
  type WorkspaceToolRun,
  type WorkspaceSourceEntry,
  type WorkspaceSourcePolicy,
  type WikiMutationPlanOntologyCandidateReview,
  type WikiMutationPlanHandoff,
  type WikiMutationPlanReview,
  type WikiMutationPlanReviewBatch,
  type WikiMutationPlanReviewBatchKind,
  type WikiMutationPlanReviewDecision,
  type WikiMutationPlanReviewItem,
  type WikiMutationPlanReviewPriority
} from "../../../packages/engine-core/src/index.ts";

export {
  LocalWorkspaceAdapter,
  createLocalWorkspaceAdapter,
  getLocalWorkspacePaths,
  type LocalWorkspacePaths
} from "./local-workspace.ts";
